### ISSUE TITLE
no navys and egypt

### ISSUE THREAD

**Issue by ahmedflix25** [generalisofficial/the-information-age#27]
every country in the game start without a navy and doesn't build any throw out the whole game.

and would you consider this for egypt an option throw national  focus or political points to militarized Sinai again without the need for world tension rise also

https://www.reddit.com/r/MillenniumDawn/comments/b7e7h9/suggestions_for_egypt/

**Comment by stuffi3000** [comment]
Yup, the first thing is on purpose.
The lastest DLC broke our Naval OOBs, so we need to recreate all of them. We'd like to make them as country specific as possible though, which obviously needs time and research.

We are also working on a more specific system which will image focus trees rather like missions instead of things you'd have to wait for a certain amount of days to happen. It will be combined with an extensive decisions system.

The Egypt part of the map hasn't been reworked yet. It will probably be made though.
@generalisofficial, the project leader might add something to that.
